apiVersion: v1
kind: Config

clusters:
- cluster:
    server:
    certificate-authority: 
  name: kube


contexts:
- context:
    cluster: 
    user:
  name: 
current-context: 

users:
- name: nitish
  user:
     client-key: 
     client-certificate: 

